#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AIR_DIR="$ROOT_DIR/apps/AI-Router-AIR"

# ──────────────────────────────────────────── #
#  Phase 1 — Prerequisites & virtual env
# ──────────────────────────────────────────── #

echo "=== Chanakya Setup ==="
echo ""
echo "Checking prerequisites..."

PYTHON=""
for candidate in python3.11 python3.12 python3.10 python3; do
    if command -v "$candidate" &>/dev/null; then
        PYTHON="$candidate"
        break
    fi
done

if [[ -z "$PYTHON" ]]; then
    echo "❌ No Python 3.10+ found. Please install Python 3.11 first."
    exit 1
fi

ver=$("$PYTHON" --version 2>&1 | grep -oP '\d+\.\d+')
major="${ver%.*}"
minor="${ver#*.}"
if [[ "$major" -lt 3 ]] || { [[ "$major" -eq 3 ]] && [[ "$minor" -lt 10 ]]; }; then
    echo "❌ Python $("$PYTHON" --version) is too old. Need 3.10+."
    exit 1
fi

echo "✓ Found $("$PYTHON" --version)"

if ! command -v pip &>/dev/null; then
    echo "❌ pip not found. Please install pip for $PYTHON."
    exit 1
fi
echo "✓ Found pip"

if ! command -v git &>/dev/null; then
    echo "❌ git not found. Please install git."
    exit 1
fi
echo "✓ Found git"

echo ""

# ── Environment setup ──
if command -v conda &>/dev/null; then
    default_env="conda"
else
    default_env="venv"
fi

read -r -p "Use conda or .venv? [conda/venv] (default: $default_env): " env_choice
env_choice="${env_choice:-$default_env}"

if [[ "$env_choice" == "conda" ]]; then
    CONDA_BASE="$(conda info --base 2>/dev/null || true)"
    # Prefer the project's conda env if it exists, regardless of which env is active
    if [[ -n "$CONDA_BASE" && -x "$CONDA_BASE/envs/chanakya/bin/python" ]]; then
        echo "✓ Using conda env 'chanakya' at $CONDA_BASE/envs/chanakya"
        PYTHON_BIN="$CONDA_BASE/envs/chanakya/bin/python"
    elif [[ -n "${CONDA_DEFAULT_ENV:-}" ]]; then
        echo "Active conda env: $CONDA_DEFAULT_ENV"
        PYTHON_BIN="python"
    else
        read -r -p "Create new conda env named [chanakya]: " conda_name
        conda_name="${conda_name:-chanakya}"
        echo "Creating conda env '$conda_name' with Python 3.11..."
        conda create -yn "$conda_name" python=3.11
        echo " Activate it manually:  conda activate $conda_name"
        echo "Then re-run this script."
        exit 0
    fi
else
    VENV_DIR="$ROOT_DIR/.venv"
    if [[ -d "$VENV_DIR" ]]; then
        echo "✓ .venv already exists at $VENV_DIR"
    else
        echo "Creating virtual environment at $VENV_DIR..."
        "$PYTHON" -m venv "$VENV_DIR"
        echo "✓ .venv created"
    fi
    PYTHON_BIN="$VENV_DIR/bin/python"
fi

echo ""
echo "Installing project dependencies..."
"$PYTHON_BIN" -m pip install --quiet --upgrade pip
"$PYTHON_BIN" -m pip install --quiet -e "$ROOT_DIR[dev]"
"$PYTHON_BIN" -m pip install --quiet -e "$AIR_DIR"
"$PYTHON_BIN" -m pip install --quiet -e "$ROOT_DIR/apps/chanakya_conversation_layer"
echo "✓ Dependencies installed"

# ──────────────────────────────────────────── #
#  Phase 2 — Config files
# ──────────────────────────────────────────── #

echo ""

if [[ ! -f "$ROOT_DIR/.env" ]]; then
    cp "$ROOT_DIR/.env.example" "$ROOT_DIR/.env"
    echo "✓ Created root .env from .env.example"
else
    echo "• Root .env already exists — skipping"
fi

if [[ ! -f "$ROOT_DIR/mcp_config_file.json" ]]; then
    if [[ -f "$ROOT_DIR/mcp_config_file.example.json" ]]; then
        cp "$ROOT_DIR/mcp_config_file.example.json" "$ROOT_DIR/mcp_config_file.json"
        echo "✓ Created mcp_config_file.json from example"
    else
        echo "⚠ No mcp_config_file.example.json found — skipping"
    fi
else
    echo "• mcp_config_file.json already exists — skipping"
fi

# ──────────────────────────────────────────── #
#  Phase 3 — LLM provider configuration
# ──────────────────────────────────────────── #

echo ""
echo "=== LLM Provider Configuration ==="
echo "This seeds apps/AI-Router-AIR/.env with your LLM backend."

read -r -p "LLM base URL (default: http://localhost:11434/v1): " llm_url
llm_url="${llm_url:-http://localhost:11434/v1}"

read -r -p "LLM API key (enter 'na' if none) [na]: " llm_key
llm_key="${llm_key:-na}"

AIR_ENV="$AIR_DIR/.env"

if [[ ! -f "$AIR_ENV" ]]; then
    # Fresh AIR .env
    {
        echo "# --- AIR provider config (generated by setup.sh) ---"
        echo "LLM_BASE_URL_1=$llm_url"
        echo "LLM_API_KEY_1=$llm_key"
        echo "SERVER_PORT=5512"
        echo "CLIENT_PORT=5511"
    } > "$AIR_ENV"
    echo "✓ Created $AIR_ENV with LLM provider"
else
    # Append LLM provider only if not already present
    if ! grep -q "LLM_BASE_URL_1" "$AIR_ENV" 2>/dev/null; then
        cat >> "$AIR_ENV" <<EOF
LLM_BASE_URL_1=$llm_url
LLM_API_KEY_1=$llm_key
EOF
        echo "✓ Added LLM provider to $AIR_ENV"
    else
        echo "• LLM_BASE_URL_1 already in $AIR_ENV — skipping (edit manually to change)"
    fi

    # Ensure SERVER_PORT / CLIENT_PORT are present
    if ! grep -q "SERVER_PORT" "$AIR_ENV" 2>/dev/null; then
        echo "SERVER_PORT=5512" >> "$AIR_ENV"
    fi
    if ! grep -q "CLIENT_PORT" "$AIR_ENV" 2>/dev/null; then
        echo "CLIENT_PORT=5511" >> "$AIR_ENV"
    fi
fi

# Also seed the root .env with a sensible default for the Chanakya app
if ! grep -q "^OPENAI_BASE_URL=" "$ROOT_DIR/.env" 2>/dev/null; then
    cat >> "$ROOT_DIR/.env" <<EOF

# --- Chanakya app configuration (generated by setup.sh) ---
OPENAI_BASE_URL="http://localhost:5512/v1"
OPENAI_CHAT_MODEL_ID="llama-3.2-3b-instruct"
OPENAI_RESPONSES_MODEL_ID="llama-3.2-3b-instruct"
OPENAI_API_KEY="na"
CHANAKYA_DEBUG=true
DATABASE_URL="sqlite:///$ROOT_DIR/chanakya_data/chanakya.db"
EOF
    echo "✓ Appended Chanakya defaults to root .env"
fi

# ──────────────────────────────────────────── #
#  Phase 4 — TTS/STT via Docker (optional)
# ──────────────────────────────────────────── #

echo ""
read -r -p "Run local Speaches/Kokoro (TTS/STT) via Docker? (~5GB download) [y/N]: " run_tts

if [[ "$run_tts" =~ ^[Yy]$ ]]; then
    if ! command -v docker &>/dev/null; then
        echo "❌ Docker not found. Skipping TTS/STT setup."
    elif ! docker compose version &>/dev/null; then
        echo "❌ docker compose plugin not found. Skipping TTS/STT setup."
    else
        echo "🎤 Starting Speaches (TTS/STT)..."
        docker compose --profile tts up -d speaches

        echo "⏳ Waiting for TTS Server to start (15s)..."
        sleep 15

        echo "⬇️  Downloading Kokoro-82M model (TTS)..."
        docker compose exec speaches uv tool run speaches-cli model download speaches-ai/Kokoro-82M-v1.0-ONNX || echo "⚠ Model download had issues — continuing"

        echo "⬇️  Downloading Faster Whisper medium model (STT)..."
        docker compose exec speaches uv tool run speaches-cli model download Systran/faster-whisper-medium.en || echo "⚠ Model download had issues — continuing"

        echo "✅ TTS/STT Services Ready."

        # Append TTS/STT to AIR .env (avoid duplicates)
        if ! grep -q "TTS_BASE_URL_1" "$AIR_ENV" 2>/dev/null; then
            cat >> "$AIR_ENV" <<EOF
TTS_BASE_URL_1=http://localhost:8969/v1
STT_BASE_URL_1=http://localhost:8969/v1
EOF
            echo "✓ TTS/STT endpoints added to $AIR_ENV"
        else
            echo "• TTS/STT endpoints already in $AIR_ENV — skipping"
        fi
    fi
fi

# ──────────────────────────────────────────── #
#  Phase 5 — Summary
# ──────────────────────────────────────────── #

echo ""
echo "═══════════════════════════════════════"
echo "  ✅ Chanakya setup complete!"
echo "═══════════════════════════════════════"
echo ""
echo "  Next steps:"
echo "    1. Edit root .env  if needed:  $ROOT_DIR/.env"
echo "    2. Edit AIR .env   if needed:  $AIR_ENV"
echo "    3. Start the stack:"
echo "       $ROOT_DIR/scripts/start_chanakya_air.sh core"
echo ""
echo "  URLs after startup:"
echo "    AIR dashboard:      http://localhost:5512"
echo "    Chanakya app:       http://localhost:5513"
echo "    Conversation layer: http://localhost:5514"
echo ""
